Longreads
microbiomedata/metaAssembly pull request #17
Opened 2024-03-27 21:25 UTC by kaijli

Added support for use with JGI long reads metaflye workflow. Updated parts are the new [choose_assembly.wdl](https://github.com/microbiomedata/metaAssembly/blob/longreads/choose_assembly.wdl) and additional outputs from long reads. Also waiting for make_info task update / mergefor the metaflye workflow [on gitlab](https://code.jgi.doe.gov/BFoster/jgi_meta_wdl/-/merge_requests/13) .

2024-04-01 16:05 UTC, mflynn-lanl approved these changes

2024-04-13 00:26 UTC, aclum approved these changes

2024-04-13 00:30 UTC, aclum commented on make_interleaved_WDL/make_interleaved_reads.wdl
> +		if file --mime -b ~{input_files[0]} | grep gzip; then
Please review all the tasks in the wdl to make sure pipeline is set if there is more than one bash executable so errors are caught by cromwell. 
command is 
'set -euo pipefail'

2024-04-13 00:33 UTC, aclum commented on test_output/test_assembly.wdl
> +   command <<<
same here all tasks should have 'set -euo pipefail' if the command block contains more than on bash command.

2024-04-13 00:33 UTC, aclum requested changes
Please review wdls to make sure 'set -euo pipefail' is set in the command block to prevent silent failures.

2024-04-18 21:13 UTC, aclum commented on test_output/test_assembly.wdl
> +   command <<<
This command block still needs a pipefail.

2024-04-18 21:41 UTC, aclum approved these changes

2024-04-18 21:55 UTC, merged