Update index.rst (Documentation)
microbiomedata/metaAssembly pull request #26
Opened 2024-11-15 18:51 UTC by vlilanl

I updated the documentation for metaAssembly.

One potential issue is that the diagram only illustrates the short reads workflow, but I'm not sure how important that is.

2024-11-15 19:31 UTC, chienchi requested changes
Thank you. Looks good. A few updates.

2024-11-15 19:31 UTC, chienchi commented on docs/index.rst
> +- `BBTools v38.94 <https://jgi.doe.gov/data-and-tools/bbtools/>`_ (License: `BSD-3-Clause-LBNL <https://bitbucket.org/berkeleylab/jgi-bbtools/src/master/license.txt>`_)
v39.03
I think we should update line 33 and 43 of jgi_assembly.wdl  to v39.03 which JGI used. 
`bbtools_container = bbtools_container`

2024-11-15 19:31 UTC, chienchi commented on docs/index.rst
> +- `metaSPAdes v3.15.0 <https://cab.spbu.ru/software/spades/>`_ (License: `GPLv2 <https://github.com/ablab/spades/blob/spades_3.15.0/assembler/GPLv2.txt>`_)
v4.0.0

2024-11-15 19:31 UTC, chienchi commented on docs/index.rst
> +- `https://hub.docker.com/r/microbiomedata/bbtools`
These are for long reads and should be added.
https://hub.docker.com/r/staphb/flye
https://hub.docker.com/r/staphb/racon
https://hub.docker.com/r/staphb/minimap2
https://hub.docker.com/r/staphb/samtools

2024-11-15 19:37 UTC, chienchi commented
Also, please help updating the README.md  which could be a brief version of the index.rst and point to [doc site ](https://nmdc-workflow-documentation.readthedocs.io/en/latest/chapters/3_MetaGAssemly_index.html) for more detailed info.

2024-11-15 22:52 UTC, chienchi approved these changes

2024-11-18 16:08 UTC, vlilanl commented
Jaws test for updated bbtools container is 91505

2024-11-18 17:44 UTC, chienchi approved these changes

2024-11-18 21:45 UTC, merged

2024-11-19 00:01 UTC, aclum commented
@vlilanl sorry for the late review. Would it be possible to show that there are two rounds of polishing with Racon in the image overview?